feat: add dropdown component
twilio-labs/match pull request #156
Opened 2021-08-10 12:00 UTC by elcuy

Adding the Match dropdown component

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2021-08-10 19:47 UTC, jayarnielsen requested changes
Nice work jumping into the design system! It looks great, but in its current state this select isn't accessible. Try the keyboard navigation with voice over turned on. I think if we're going to do a fully custom dropdown we should use something like [Downshift](https://github.com/downshift-js/downshift) to help iron out much of those kinks. Alternatively we style a standard select element as best we can and don't try to go fully custom this go-round. I'm also concerned about the mobile experience. I wonder if it would lead to a better experience if we swapped in the standard select element on mobile and only used the custom select element on desktop sizes. Selects behave very differently on ios and android, so it might be best to retain that behavior. I believe this is how material-ui does it.

2021-08-10 23:07 UTC, serenabux commented on packages/match-components/src/select/styles.ts
> +    color: ${themeGet("textColors.tertiary")};
It seems like the placeholder text is showing up as textColors.primary instead of textColors.tertiary, but textColors.tertiary is correct.

2021-08-10 23:09 UTC, serenabux commented on packages/match-components/src/select/styles.ts
> +  font-size: ${themeGet("fontSizes.scale80")};
Can we use fontSizes.scale100 for the text inside the select input?

2021-08-10 23:13 UTC, serenabux commented on packages/match-components/src/select/select.tsx
> +            size={LabelSize.SMALL}
Can we actually use LabelSize.NORMAL? Also it would be incredible if you could update the input component to also use LabelSize.NORMAL

2021-08-10 23:16 UTC, serenabux commented on packages/match-components/src/select/styles.ts
> +  font-weight: ${themeGet("fontWeights.regular")};
Could we actually use fontWeights.medium for within the select? It would also be amazing if you could update it for within the input component

2021-08-11 15:42 UTC, jayarnielsen commented
Last couple of things: could we add a storybook story with the select in an error state? And can we add a documentation page to the website?

2021-08-11 19:07 UTC, elcuy commented
@jayarnielsen Sure thing! Adding it now

2021-08-16 18:06 UTC, jayarnielsen submitted a review, later dismissed
Looks good!

2021-08-16 18:20 UTC, merged